apiVersion: v1
kind: Service
metadata:
  name: focusflow-service
  namespace: default
spec:
  selector:
    app: focusflow-app
  ports:
    - protocol: TCP
      port: 80         # Port Traefik looks for
      targetPort: 5000 # Port your Python app is running on
  type: ClusterIP