apiVersion: v1
kind: Service
metadata:
  name: focusflow-service
  namespace: default
spec:
  selector:
    app: focusflow-app
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 5000
#      nodePort: 30500
#  type: NodePort